import json
import os
from itertools import combinations
from typing import List, Callable

from analysis.analysis_utils import analysis_utils
from analysis.analyze_different_llms.compare_summaries import compare_summaries_utils
from analysis.analyze_different_llms.compare_summaries.compare_summaries_utils import (
    Summary,
)
from common.summarize_transcript import summarize_utils
from common.transcribe_audio_chunks import transcribe_audio_chunks_utils
from common.utils import utils


def compare(
    video_id: str,
    create_video_base_path: Callable[[str], str],
    create_comparison_path: Callable[[str], str],
    considered_models: List[str],
    create_summary_as_json_path: Callable[[str, str], str],
    create_audio_chunks_data_path: Callable[[str], str],
    create_transcript_data_path: Callable[[str], str],
    llm_evaluator_system_and_user_prompt_to_response: Callable[[str, str], str],
    create_comparison_points_path: Callable[[str], str],
) -> None:
    """
    For a given video, retrieves all summaries generated by the different LLM models and compares them pairwise
    (1-vs-1) with respect to faithfulness and coverage given the transcripts as source of truth. Each pair is also
    evaluated in reverse order to reduce ordering effects.

    For each comparison, the LLM judge produces a short explanation for faithfulness and coverage and one of three
    outcomes: A wins, B wins, or draw. A win yields 1 point for the winning model, while a draw yields 0.5 points for
    each model. The results from both directions (A vs. B and B vs. A) are aggregated as follows: if both directions
    agree, that result is used; if one direction yields a win and the reverse yields a draw, the win is kept;
    if the directions contradict each other, the comparison is treated as a draw.

    The results of the comparisons are stored as a JSON file under comparison_path. The points for each LLM model are
    persisted in a JSON file under the comparison_points_path.

    Args:
        video_id (str):
            Identifier of the video to be summarized.
        create_video_base_path (Callable[[str], str]):
            Function that takes a video id as input and creates a path to a folder containing all data related to summarizing the video and evaluating the summary.
        create_comparison_path (Callable[[str], str]):
            Function that takes video_base_path as input and creates a path to the JSON file where all the comparison results are stored.
        considered_models (List[str]):
            All LLM model IDs that are considered for pairwise comparison.
        create_summary_as_json_path (Callable[[str, str], str]):
            Function that takes video_base_path and llm_model_id as input and creates a path to the summary JSON file.
        create_audio_chunks_data_path (Callable[[str], str]):
            Function that takes video_base_path as input and creates a path to the audio chunks data JSON file.
        create_transcript_data_path (Callable[[str], str]):
            Function that takes video_base_path as input and creates a path to the transcript data JSON file.
        llm_evaluator_system_and_user_prompt_to_response (Callable[[str, str], str]):
            Strong LLM model that acts as AI-as-a-judge that evaluates the summaries. System prompt and user prompt are passed as input and the LLM response is returned.
        create_comparison_points_path (Callable[[str], str]):
            Function that takes video_base_path as input and creates a path to the JSON file where all the resulting comparison points are stored.

        Returns:
            None
    """

    print(f"compare summaries for video {video_id}...")

    video_base_path = create_video_base_path(video_id)

    comparison_path = create_comparison_path(video_base_path)

    os.makedirs(os.path.dirname(comparison_path), exist_ok=True)

    summaries = [
        Summary(
            llm_model_id=llm_model_id,
            summary_as_json_path=create_summary_as_json_path(
                video_base_path, llm_model_id
            ),
        )
        for llm_model_id in considered_models
    ]

    # get transcript snippets

    audio_chunks_data_path = create_audio_chunks_data_path(video_base_path)
    transcript_data_path = create_transcript_data_path(video_base_path)

    transcript_snippets = transcribe_audio_chunks_utils.get_transcript_snippets(
        audio_chunks_data_path=audio_chunks_data_path,
        transcript_data_path=transcript_data_path,
    )

    # handle pairs

    pairs = list(combinations(summaries, 2))

    print(f"num pairs to compare: {len(pairs)}")

    for pair in pairs:
        _compare_two_summaries_and_there_reverse(
            summary_a=pair[0],  # type: ignore
            summary_b=pair[1],  # type: ignore
            comparison_path=comparison_path,
            transcript_snippets=transcript_snippets,
            llm_evaluator_system_and_user_prompt_to_response=llm_evaluator_system_and_user_prompt_to_response,
        )

    llm_model_id_to_points = _calculate_points(
        comparison_path=comparison_path, summaries=summaries
    )

    comparison_points_path = create_comparison_points_path(video_base_path)

    utils.save_json(
        path=comparison_points_path,
        json_for_saving=llm_model_id_to_points,
    )

    print(f"...compared summaries for video {video_id}")


def _compare_two_summaries_and_there_reverse(
    summary_a: Summary,
    summary_b: Summary,
    comparison_path: str,
    transcript_snippets: List[str],
    llm_evaluator_system_and_user_prompt_to_response: Callable[[str, str], str],
) -> None:
    """
    Compares two summaries pairwise (1-vs-1) with respect to faithfulness and coverage, using the video transcript as
    the source of truth. Evaluates both directions (A vs. B and B vs. A) and stores the result in a JSON file at comparison_path.

    Args:
        summary_a (Summary):
            Summary A to be compared.
        summary_b (Summary):
            Summary B to be compared.
        comparison_path (str):
            Path to the JSON file where all the comparison results are stored.
        transcript_snippets (List[str]):
            Transcript consisting of snippets from the video.
        llm_evaluator_system_and_user_prompt_to_response (Callable[[str, str], str]):
            Strong LLM model that acts as AI-as-a-judge that evaluates the summaries. System prompt and user prompt
            are passed as input and the LLM response is returned.

        Returns:
            None
    """
    print(
        f"comparing summaries {summary_a.llm_model_id} vs. {summary_b.llm_model_id}..."
    )

    # handle already compared

    if compare_summaries_utils.are_two_summaries_already_compared(
        comparison_path=comparison_path,
        summary_a=summary_a,
        summary_b=summary_b,
    ):
        print(f"...summaries already compared")
        return

    # compare a <-> b and b <-> a

    (
        faithfulness_winner_a_b,
        faithfulness_explanation_a_b,
        coverage_winner_a_b,
        coverage_explanation_a_b,
    ) = _compare_summary_a_and_b(
        summary_a=summary_a,
        summary_b=summary_b,
        transcript_snippets=transcript_snippets,
        llm_evaluator_system_and_user_prompt_to_response=llm_evaluator_system_and_user_prompt_to_response,
    )

    (
        faithfulness_winner_b_a,
        faithfulness_explanation_b_a,
        coverage_winner_b_a,
        coverage_explanation_b_a,
    ) = _compare_summary_a_and_b(
        summary_a=summary_b,
        summary_b=summary_a,
        transcript_snippets=transcript_snippets,
        llm_evaluator_system_and_user_prompt_to_response=llm_evaluator_system_and_user_prompt_to_response,
    )

    comparison_result = {
        "model_id_a": summary_a.llm_model_id,
        "model_id_b": summary_b.llm_model_id,
        "a_b": {
            "winner_faithfulness": faithfulness_winner_a_b,
            "faithfulness_explanation": faithfulness_explanation_a_b,
            "winner_coverage": coverage_winner_a_b,
            "coverage_explanation": coverage_explanation_a_b,
        },
        "b_a": {
            "winner_faithfulness": faithfulness_winner_b_a,
            "faithfulness_explanation": faithfulness_explanation_b_a,
            "winner_coverage": coverage_winner_b_a,
            "coverage_explanation": coverage_explanation_b_a,
        },
        "faithfulness_is_commutative": analysis_utils.are_results_commutative(
            a_b=faithfulness_winner_a_b, b_a=faithfulness_winner_b_a
        ),
        "coverage_is_commutative": analysis_utils.are_results_commutative(
            a_b=coverage_winner_a_b, b_a=coverage_winner_b_a
        ),
    }

    # save result in json

    compare_summaries_utils.add_pair_to_comparison_pairs(
        comparison_path=comparison_path,
        comparison_pair=comparison_result,
    )

    print(f"...compared summaries")


def _compare_summary_a_and_b(
    summary_a: Summary,
    summary_b: Summary,
    transcript_snippets: List[str],
    llm_evaluator_system_and_user_prompt_to_response: Callable[[str, str], str],
) -> tuple[str, str, str, str]:
    """
    Compares two summaries pairwise (1-vs-1) with respect to faithfulness and coverage, using the video transcript as
    the source of truth.

    Args:
        summary_a (Summary):
            Summary A to be compared.
        summary_b (Summary):
            Summary B to be compared.
        transcript_snippets (List[str]):
            Transcript consisting of snippets from the video.
        llm_evaluator_system_and_user_prompt_to_response (Callable[[str, str], str]):
            Strong LLM model that acts as AI-as-a-judge that evaluates the summaries. System prompt and user prompt
            are passed as input and the LLM response is returned.

        Returns:
            tuple[str, str, str, str]:
                The result for the faithfulness comparison (winner A, B, or draw), a short explanation,
                and the same for coverage.
    """

    # create system prompt

    system_prompt = """You are an AI judge that compares two summaries with regard to faithfulness and coverage.

YOU WILL RECEIVE:

* A reference snippet from a video that consists of several consecutive snippet snippets that may overlap at the beginning and end.
* Two candidate summaries (A and B) based on the provided snippet.

YOUR TASK:

* With respect to the available snippet, compare summary A vs. B in two categories.
* There are three possible results: A is better than B, B is better than A, or it is a draw.
* Your judgment must be symmetric.
* Swapping summary A and summary B must not change the result, except for swapping the labels A and B.

1. Category FAITHFULNESS: Faithfulness evaluates whether a summary contains only information supported by the source text, without inventing, adding, or contradicting facts.
2. Category COVERAGE: Coverage evaluates whether a summary includes the main ideas, arguments, and conclusions from the source text, without omitting essential information.

For each category, give a short explanation for your result.

OUTPUT FORMAT:

Do only output the following JSON

{
    "faithfulness": {
        "explanation": "string",
        "winner": "A" | "B" | "draw"
    },
    "coverage": {
        "explanation": "string",
        "winner": "A" | "B" | "draw"
    }
}"""

    # create user prompt

    user_prompt_with_placeholders = """TRANSCRIPT:
        
{{transcripts}}
        
----------------------------------
    
CANDIDATE SUMMARY A:
        
{{candidate_summary_a}}
        
----------------------------------
    
CANDIDATE SUMMARY B:
        
{{candidate_summary_b}}"""

    candidate_summary_a_placeholder_value = summarize_utils.get_summary(
        summary_as_json_path=summary_a.summary_as_json_path
    )

    candidate_summary_b_placeholder_value = summarize_utils.get_summary(
        summary_as_json_path=summary_b.summary_as_json_path
    )

    user_prompt = (
        user_prompt_with_placeholders.replace(
            "{{transcripts}}",
            analysis_utils.create_transcript_from_snippets(
                transcript_snippets=transcript_snippets
            ),
        )
        .replace("{{candidate_summary_a}}", candidate_summary_a_placeholder_value)
        .replace("{{candidate_summary_b}}", candidate_summary_b_placeholder_value)
    )

    # perform comparison

    response = llm_evaluator_system_and_user_prompt_to_response(
        system_prompt, user_prompt
    )

    response_as_json = json.loads(response)

    return (
        response_as_json["faithfulness"]["winner"],
        response_as_json["faithfulness"]["explanation"],
        response_as_json["coverage"]["winner"],
        response_as_json["coverage"]["explanation"],
    )


def _calculate_points(
    comparison_path: str,
    summaries: List[Summary],
) -> dict[str, dict[str, int]]:
    """
    Calculates the resulting points for each LLM model based on the comparison results stored in comparison_path.

    Args:
        comparison_path (str):
            Path to the JSON file where all the comparison results are stored.
        summaries (List[Summary]):
            List of summaries that have been compared.

        Returns:
            dict[str, dict[str, int]]:
                llm_model_id to points (second dict is for faithfulness and coverage).
    """

    # init points to 0
    model_id_to_points: dict[str, dict[str, int]] = {}
    for summary in summaries:
        model_id_to_points[summary.llm_model_id] = {
            "faithfulness": 0,
            "coverage": 0,
        }

    pairs = compare_summaries_utils.get_comparison_pairs(
        comparison_path=comparison_path
    )

    for pair in pairs:
        model_id_a = pair["model_id_a"]
        model_id_b = pair["model_id_b"]

        if pair["faithfulness_is_commutative"] >= 1:
            if pair["a_b"]["winner_faithfulness"] == "A":
                model_id_to_points[model_id_a]["faithfulness"] += 1
            elif pair["a_b"]["winner_faithfulness"] == "B":
                model_id_to_points[model_id_b]["faithfulness"] += 1
            else:
                model_id_to_points[model_id_a]["faithfulness"] += 0.5
                model_id_to_points[model_id_b]["faithfulness"] += 0.5
        else:
            model_id_to_points[model_id_a]["faithfulness"] += 0.5
            model_id_to_points[model_id_b]["faithfulness"] += 0.5

        if pair["coverage_is_commutative"] >= 1:
            if pair["a_b"]["winner_coverage"] == "A":
                model_id_to_points[model_id_a]["coverage"] += 1
            elif pair["a_b"]["winner_coverage"] == "B":
                model_id_to_points[model_id_b]["coverage"] += 1
            else:
                model_id_to_points[model_id_a]["coverage"] += 0.5
                model_id_to_points[model_id_b]["coverage"] += 0.5
        else:
            model_id_to_points[model_id_a]["coverage"] += 0.5
            model_id_to_points[model_id_b]["coverage"] += 0.5

    return model_id_to_points
